apiVersion: v1
kind: Secret
metadata:
  name: openfindbearings-identity-secrets
  namespace: openfindbearings
type: Opaque
stringData:
  # 数据库连接串
  ConnectionStrings__DefaultConnection: "<db_identity 连接串>"
  # 证书密码
  openIddict__certpwd: "<证书密码>"
